services:
  word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql

  document-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-document:/var/opt/mssql

  occurrence-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-occurrence:/var/opt/mssql

  short-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-short:/var/opt/mssql

  medium-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-medium:/var/opt/mssql

  long-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-long:/var/opt/mssql

  indexer-service:
    build:
      context: .
      dockerfile: Indexer/Dockerfile
    depends_on:
      - word-db

  console-service:
    build:
      context: ./ConsoleSearch
      dockerfile: Dockerfile
    depends_on:
      - word-db

  word-service:
    build:
      context: ./WordService
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - word-db
      - seq
      - zipkin
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Seq__ServerUrl=http://seq:5341
      - Zipkin__Endpoint=http://zipkin:9411/api/v2/spans

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  mssql-data:
  mssql-document:
  mssql-occurrence:
  mssql-data-short:
  mssql-data-medium:
  mssql-data-long:
